
services:
    php82cli:
        build: ./
        container_name: symfony-php82cli-bookworm
        restart: always
        ports:
            - 8080:8000
            - 5173:5173 #package.json "scripts": {"dev": "vite --host"}
        links:
            - database
        volumes:
            - ./:/var/www/html
        tty: true
        # symfony server:start
        # php -S php82cli:8000 -t public
        # php artisan serve --host php82cli
        # php yii serve php82cli --port=8000
    database:
        image: mariadb:11.2-jammy
        container_name: mariadb-jammy
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: symfony
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: phpmyadmin
    phpmyadmin:
        image: phpmyadmin:5.2-apache
        container_name: phpmyadmin-buster
        restart: always
        links:
            - database
        ports:
            - 8084:80
        environment:
            PMA_HOST: database
            PMA_USER: phpmyadmin
            PMA_PASSWORD: phpmyadmin
        
